filter:
    excluded_paths: [_tests, _tools]

tools:
    external_code_coverage:
        timeout: 1800
        runs: 1

    php_code_sniffer: true

     # PHP Mess Detector (http://phpmd.org)
    php_mess_detector: true

    # Security Advisory Checker
    sensiolabs_security_checker: true

    # Analyzes the size and structure of a PHP project
    php_pdepend:
        enabled: true
        excluded_dirs: [_tests, _tools]

    # Analyzes the size and structure of a PHP project
    php_loc:
        enabled: true
        excluded_dirs: [_tests, _tools]

    # Copy/Paste Detector
    php_cpd:
        enabled: true
        excluded_dirs: [_tests, _tools]

    # Runs Scrutinizer's PHP Analyzer Tool
    php_analyzer:
        enabled: true
        excluded_dirs: [_tests, _tools]
